export const NEXT_PUBLIC_BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;
export const NEXT_PUBLIC_HST_MAP_URL = process.env.NEXT_PUBLIC_HST_MAP_URL;
export const NEXT_PUBLIC_HST_MAP_POKHARA_URL =
  process.env.NEXT_PUBLIC_HST_MAP_POKHARA_URL;
export const NEXT_PUBLIC_HST_POKHARA_URL =
  process.env.NEXT_PUBLIC_HST_POKHARA_URL;
export const NEXT_PUBLIC_TRIP_ADVISOR_REVIEW_URL =
  process.env.NEXT_PUBLIC_TRIP_ADVISOR_REVIEW_URL;
export const NEXT_PUBLIC_HST_APP_URL = process.env.NEXT_PUBLIC_HST_APP_URL;
