name: HST

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.6.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/dashboard/package-lock.json

      # ------------------------------
      # BACKEND SETUP
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./backend/dashboard
        run: npm install

      - name: Create backend .env file
        run: |
          echo "${{ secrets.PROD_BACKEND_ENV }}" > backend/dashboard/.env
          echo "Created backend/dashboard/.env with:"
          cat backend/dashboard/.env

      - name: Start backend with PM2
        working-directory: ./backend/dashboard
        run: |
          /home/ubuntu/.nvm/versions/node/v22.18.0/bin/pm2 restart backend --update-env || /home/ubuntu/.nvm/versions/node/v22.18.0/bin/pm2 start app.js --name backend --update-env

